### ISSUE TITLE
Skill: (2) Use and organize SCSS in Rails

### ISSUE THREAD

**Issue by 0kendyl0** [0kendyl0/tc359_rails_final#4]
https://shrouded-stream-5138.herokuapp.com/

@chrisvfritz

**Comment by chrisvfritz** [comment]
:+1: Looks good! This isn't something you have to update, but for future reference, Rails actually lets you leave off the underscores for SCSS partials if you want.

**Comment by chrisvfritz** [comment]
Oh, and you now officially have a 4.0. Congratulations! :smiley: :tada: :balloon:
